

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/zynq_ultra_ps_e_0/U0/pl_clk0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {reg_o_evr[tst_trigwid][0]} {reg_o_evr[tst_trigwid][1]} {reg_o_evr[tst_trigwid][2]} {reg_o_evr[tst_trigwid][3]} {reg_o_evr[tst_trigwid][4]} {reg_o_evr[tst_trigwid][5]} {reg_o_evr[tst_trigwid][6]} {reg_o_evr[tst_trigwid][7]} {reg_o_evr[tst_trigwid][8]} {reg_o_evr[tst_trigwid][9]} {reg_o_evr[tst_trigwid][10]} {reg_o_evr[tst_trigwid][11]} {reg_o_evr[tst_trigwid][12]} {reg_o_evr[tst_trigwid][13]} {reg_o_evr[tst_trigwid][14]} {reg_o_evr[tst_trigwid][15]} {reg_o_evr[tst_trigwid][16]} {reg_o_evr[tst_trigwid][17]} {reg_o_evr[tst_trigwid][18]} {reg_o_evr[tst_trigwid][19]} {reg_o_evr[tst_trigwid][20]} {reg_o_evr[tst_trigwid][21]} {reg_o_evr[tst_trigwid][22]} {reg_o_evr[tst_trigwid][23]} {reg_o_evr[tst_trigwid][24]} {reg_o_evr[tst_trigwid][25]} {reg_o_evr[tst_trigwid][26]} {reg_o_evr[tst_trigwid][27]} {reg_o_evr[tst_trigwid][28]} {reg_o_evr[tst_trigwid][29]} {reg_o_evr[tst_trigwid][30]} {reg_o_evr[tst_trigwid][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {reg_o_evr[tst_trigdly][0]} {reg_o_evr[tst_trigdly][1]} {reg_o_evr[tst_trigdly][2]} {reg_o_evr[tst_trigdly][3]} {reg_o_evr[tst_trigdly][4]} {reg_o_evr[tst_trigdly][5]} {reg_o_evr[tst_trigdly][6]} {reg_o_evr[tst_trigdly][7]} {reg_o_evr[tst_trigdly][8]} {reg_o_evr[tst_trigdly][9]} {reg_o_evr[tst_trigdly][10]} {reg_o_evr[tst_trigdly][11]} {reg_o_evr[tst_trigdly][12]} {reg_o_evr[tst_trigdly][13]} {reg_o_evr[tst_trigdly][14]} {reg_o_evr[tst_trigdly][15]} {reg_o_evr[tst_trigdly][16]} {reg_o_evr[tst_trigdly][17]} {reg_o_evr[tst_trigdly][18]} {reg_o_evr[tst_trigdly][19]} {reg_o_evr[tst_trigdly][20]} {reg_o_evr[tst_trigdly][21]} {reg_o_evr[tst_trigdly][22]} {reg_o_evr[tst_trigdly][23]} {reg_o_evr[tst_trigdly][24]} {reg_o_evr[tst_trigdly][25]} {reg_o_evr[tst_trigdly][26]} {reg_o_evr[tst_trigdly][27]} {reg_o_evr[tst_trigdly][28]} {reg_o_evr[tst_trigdly][29]} {reg_o_evr[tst_trigdly][30]} {reg_o_evr[tst_trigdly][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {reg_o_dma[trig_dly][0]} {reg_o_dma[trig_dly][1]} {reg_o_dma[trig_dly][2]} {reg_o_dma[trig_dly][3]} {reg_o_dma[trig_dly][4]} {reg_o_dma[trig_dly][5]} {reg_o_dma[trig_dly][6]} {reg_o_dma[trig_dly][7]} {reg_o_dma[trig_dly][8]} {reg_o_dma[trig_dly][9]} {reg_o_dma[trig_dly][10]} {reg_o_dma[trig_dly][11]} {reg_o_dma[trig_dly][12]} {reg_o_dma[trig_dly][13]} {reg_o_dma[trig_dly][14]} {reg_o_dma[trig_dly][15]} {reg_o_dma[trig_dly][16]} {reg_o_dma[trig_dly][17]} {reg_o_dma[trig_dly][18]} {reg_o_dma[trig_dly][19]} {reg_o_dma[trig_dly][20]} {reg_o_dma[trig_dly][21]} {reg_o_dma[trig_dly][22]} {reg_o_dma[trig_dly][23]} {reg_o_dma[trig_dly][24]} {reg_o_dma[trig_dly][25]} {reg_o_dma[trig_dly][26]} {reg_o_dma[trig_dly][27]} {reg_o_dma[trig_dly][28]} {reg_o_dma[trig_dly][29]} {reg_o_dma[trig_dly][30]} {reg_o_dma[trig_dly][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list evr_dma_trig]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list evr/BUFG_GT_rx_n_0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list tst_trig]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_BUFG_GT_rx_n_0]
